#-------------------- Server ----------------------
server.port=8080

#-------------------- Redis ----------------------
redis.host=172.20.1.2
redis.port=6379

#-------------------- Spring Data Source ----------------------
spring.datasource.username=trader
spring.datasource.password=ok
spring.sql.init.platform=postgresql
spring.datasource.driver-class-name=org.postgresql.Driver

#-------------------- MyBatis ----------------------
mybatis.config-location=classpath:mybatis/mybatis.conf.xml

#-------------------- Thymeleaf ----------------------
spring.thymeleaf.check-template=true
spring.thymeleaf.check-template-location=true
spring.thymeleaf.servlet.content-type=text/html
spring.thymeleaf.enabled=true
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.suffix=.html
# spring.thymeleaf.excluded-view-names:
# spring.thymeleaf.mode: HTML5
# spring.thymeleaf.template-resolver-order:
# spring.thymeleaf.view-names:

# static content from filesystem first
#spring.web.resources.static-locations[0]=file:src/main/resources/static/
#spring.web.resources.static-locations[1]=classpath:/static/

#-------------------- Adapters ----------------------
adapter.stockmarket.from-date=2000-01-01
#adapter.nordnet.nordnet-host=http://172.20.1.5:8082
adapter.nordnet.nordnet-host=http://localhost:8082

#-------------------- Profiles ----------------------
#spring.profiles.active = hilo
#spring.profiles.active = prod
spring.profiles.active=demo
